name: CI

on:
  push:
    branches:
      - eas-cli
  workflow_dispatch:

jobs:
  build-eas:
    # Use macOS to get the correct platform specific dependencies
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: linrongda/eas-cli
          ref: feat/submit-by-local-machine

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install Dependencies
        run: |
          brew install python-setuptools
          yarn install --frozen-lockfile --check-files
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1

      - name: Build EAS CLI
        run: yarn build

      - name: Build tarballs
        working-directory: ${{ github.workspace }}/packages/eas-cli
        run: |
          yarn pretarball-ci
          yarn oclif pack:tarballs --no-xz --targets darwin-arm64

      - name: Move darwin-arm64 tarball to artifact folder
        run: |
          filename=$(ls eas-*-arm64.tar.gz)
          mv $filename ${{ github.workspace }}/packages/eas-cli/dist/eas-cli.tar.gz
        working-directory: ${{ github.workspace }}/packages/eas-cli/dist

      - name: Upload darwin-arm64 tarball
        uses: actions/upload-artifact@v4
        with:
          path: packages/eas-cli/dist/eas-cli.tar.gz
          name: eas-cli