name: CI

on:
  push:
    branches:
      - eas-cli
  workflow_dispatch:

jobs:
  build-eas:
    # Use macOS to get the correct platform specific dependencies
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v6
        with:
          repository: linrongda/eas-cli
          ref: feat/submit-by-local-machine

      - name: Enable Corepack and prepare Yarn
        run: |
          corepack enable
          corepack prepare yarn@4.12.0 --activate

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install Dependencies
        run: |
          yarn install --immutable

      - name: Build EAS CLI
        run: yarn build 

      - name: Pack EAS CLI
        run: |
          tar -czf eas-cli.tar.gz eas-cli/
        working-directory: ${{ github.workspace }}/packages

      - name: Upload EAS CLI tarball
        uses: actions/upload-artifact@v7
        with:
          path: packages/eas-cli.tar.gz
          name: eas-cli